import type { Product } from "@/types/product";

export const PRODUCTS: Product[] = [
  {
    id: "CUR253590Z",
    slug: "curad-xeroform-sterile-nonadherent-gauze-dressings",
    sku: "CUR253590Z",
    name: "CURAD Xeroform Sterile Nonadherent Gauze Dressings",
    description: "DRESSING,GAUZE,XEROFORM,CURAD,5X9,ST",
    category: "Impregnated Gauzes",
    manufacturer: "MEDLINE",
    price: 46.61,
    weight: "1.35 LB",
    image: "/ImageWithFallback.png",
    rating: 4.5,
    reviewCount: 30,
    workflowType: "self-pay",
  },
  {
    id: "MSC8801EPH",
    slug: "puracol-ultra-powder-collagen-wound-dressings",
    sku: "MSC8801EPH",
    name: "Puracol Ultra Powder Collagen Wound Dressings",
    description: "COLLAGEN, PARTICLES, PURACOL ULTRA, 1G",
    category: "Puracol Ultra",
    manufacturer: "MEDLINE",
    price: 23.22,
    weight: "0.025 LB",
    image: "/ImageWithFallback.png",
    rating: 4.2,
    reviewCount: 15,
    workflowType: "self-pay",
  },
  {
    id: "FG2300H",
    slug: "fitguard-prime-nitrile-exam-gloves",
    sku: "FG2300H",
    name: "FitGuard Prime Nitrile Exam Gloves",
    description: "GLOVE, EXAM, NITRILE, PF, W/ FILM, X",
    category: "Nitrile Exam Gloves",
    manufacturer: "MEDLINE",
    price: 23.17,
    weight: "1.65 LB",
    image: "/ImageWithFallback.png",
    rating: 4.8,
    reviewCount: 120,
    workflowType: "self-pay",
  },
  {
    id: "MSC6444EPZ",
    slug: "optilock-nonadhesive-super-absorbent-wound-dressings",
    sku: "MSC6444EPZ",
    name: "OptiLock Nonadhesive Super Absorbent Wound Dressings",
    description: "OPTILOCK,NON-ADHESIVE,4X4",
    category: "Absorbent Dressings",
    manufacturer: "MEDLINE",
    price: 44.65,
    weight: "0.285 LB",
    image: "/ImageWithFallback.png",
    rating: 4.4,
    reviewCount: 45,
    workflowType: "self-pay",
  },
  {
    id: "MDR630EXTN",
    slug: "medline-bed-extension-kits",
    sku: "MDR630EXTN",
    name: "Medline Bed Extension Kits",
    description: "KIT,EXTENSION,F/ 2E/3E & 2L/3L BEDS",
    category: "Bed Parts",
    manufacturer: "MEDLINE",
    price: 42.60,
    weight: "12.787 LB",
    image: "/ImageWithFallback.png",
    rating: 4.1,
    reviewCount: 12,
    workflowType: "self-pay",
  },
  {
    id: "O-NNEC801",
    slug: "omron-nebulizer-system",
    sku: "O-NNEC801",
    name: "Omron Nebulizer System",
    description: "DBF-SEE EMONEC801H SYSTEM,NEBULIZER,COMP",
    category: "Emerson Healthcare L",
    manufacturer: "OMRON HEALTHCARE INC",
    price: 41.94,
    weight: "1.65 LB",
    image: "/ImageWithFallback.png",
    rating: 4.6,
    reviewCount: 88,
    workflowType: "self-pay",
  },
  {
    id: "MPHSFTY21Z",
    slug: "medline-push-button-safety-lancets-21g",
    sku: "MPHSFTY21Z",
    name: "Medline Push Button Safety Lancets",
    description: "LANCET,SAFETY,21G,1.8MM,PUSH BUTTON",
    category: "Lancets",
    manufacturer: "MEDLINE",
    price: 38.96,
    weight: "1.15 LB",
    image: "/ImageWithFallback.png",
    rating: 4.3,
    reviewCount: 52,
    workflowType: "self-pay",
  },
  {
    id: "CUR253590H",
    slug: "xeroform-sterile-nonadherent-gauze-5x9",
    sku: "CUR253590H",
    name: "CURAD Xeroform Sterile Nonadherent Gauze Dressings",
    description: "DRESSING,GAUZE,XEROFORM,CURAD,5X9,ST",
    category: "Impregnated Gauzes",
    manufacturer: "MEDLINE",
    price: 1.15,
    weight: "0.027 LB",
    image: "/ImageWithFallback.png",
    rating: 4.5,
    reviewCount: 10,
    workflowType: "self-pay",
  },
  {
    id: "MDS86222BRZX4",
    slug: "medline-quad-canes-small-base",
    sku: "MDS86222BRZX4",
    name: "Medline Quad Canes with Small Base",
    description: "CANE, QUAD, SMALL BASE, BRONZE",
    category: "Canes/Quad Canes",
    manufacturer: "MEDLINE",
    price: 34.80,
    weight: "0.001 LB",
    image: "/ImageWithFallback.png",
    rating: 4.0,
    reviewCount: 22,
    workflowType: "self-pay",
  },
  {
    id: "HCS4515B",
    slug: "soft-touch-oxygen-cannulas",
    sku: "HCS4515B",
    name: "Medline Soft-Touch Oxygen Cannulas",
    description: "DBD-CANNULA,ADULT,SOFT-TOUCH,25TUBE,SC",
    category: "H O2 CANNULAS",
    manufacturer: "MEDLINE",
    price: 34.56,
    weight: "8.8 LB",
    image: "/ImageWithFallback.png",
    rating: 4.7,
    reviewCount: 64,
    workflowType: "self-pay",
  },
  {
    id: "MSCPRC21616CS",
    sku: "MSCPRC21616CS",
    slug: "gel-foam-wheelchair-cushions",
    name: "Medline Gel Foam Wheelchair Cushions",
    description: "CUSHION,W/C, GEL FOAM CUSHION,16X16X2,CS",
    category: "Cushions and Wheel C",
    manufacturer: "MEDLINE",
    price: 68.58,
    weight: "16.3 LB",
    image: "/ImageWithFallback.png",
    rating: 4.5,
    reviewCount: 38,
    workflowType: "self-pay",
  },
  {
    id: "HH70G04",
    sku: "HH70G04",
    slug: "spectrum-advanced-hand-sanitizer",
    name: "Spectrum Advanced 70% Ethyl Alcohol Gel Hand Sanitizer",
    description: "HAND SANITIZER,GEL,SPECTRUM 70%,4OZ",
    category: "Spectrum Sanitizers",
    manufacturer: "MEDLINE",
    price: 34.23,
    weight: "7.6 LB",
    image: "/ImageWithFallback.png",
    rating: 4.9,
    reviewCount: 210,
    workflowType: "self-pay",
  },
  {
    id: "ULT101253Z",
    slug: "ultimed-tuberculin-safety-syringes",
    sku: "ULT101253Z",
    name: "Ultimed Tuberculin Safety Syringes",
    description: "SYRINGE,SAFETY,TB,25GX5/8,1ML",
    category: "Insulin/TB Safety Sy",
    manufacturer: "ULTIMED INC",
    price: 25.74,
    weight: "0.8 LB",
    image: "/ImageWithFallback.png",
    rating: 4.4,
    reviewCount: 25,
    workflowType: "self-pay",
  },
  {
    id: "MSC263754",
    slug: "fitright-aloe-personal-cleansing-wipes",
    sku: "MSC263754",
    name: "FitRight Aloe Personal Cleansing Wipes",
    description: "WIPE, WET, SCENTED, 8X10, 68/PK",
    category: "Wet Wipes",
    manufacturer: "MEDLINE",
    price: 27.09,
    weight: "12.3 LB",
    image: "/ImageWithFallback.png",
    rating: 4.6,
    reviewCount: 94,
    workflowType: "self-pay",
  },
  {
    id: "MPH100030Z",
    slug: "medline-general-purpose-lancets",
    sku: "MPH100030Z",
    name: "Medline General Purpose Lancets",
    description: "LANCET,GENERAL PURPOSE 30G",
    category: "Lancets",
    manufacturer: "MEDLINE",
    price: 3.97,
    weight: "0.167 LB",
    image: "/ImageWithFallback.png",
    rating: 4.1,
    reviewCount: 33,
    workflowType: "self-pay",
  },
  {
    id: "MDSP105612",
    slug: "cando-exercise-bands-red",
    sku: "MDSP105612",
    name: "Medline CanDo Non-Latex Exercise Bands",
    description: "BAND,EXERCISE,CANDO,LF,6YD,RED,LVL2",
    category: "MB Exercise Supplies",
    manufacturer: "MEDLINE",
    price: 23.54,
    weight: "0.5 LB",
    image: "/ImageWithFallback.png",
    rating: 4.3,
    reviewCount: 18,
    workflowType: "self-pay",
  },
  {
    id: "WCABELT",
    slug: "replacement-wheelchair-safety-belts",
    sku: "WCABELT",
    name: "Medline Replacement Wheelchair Safety Belts",
    description: "BELT,SAFETY,F/WHLCHAIR",
    category: "Wheelchair Part/Accs",
    manufacturer: "MEDLINE",
    price: 3.91,
    weight: "0.244 LB",
    image: "/ImageWithFallback.png",
    rating: 4.5,
    reviewCount: 42,
    workflowType: "self-pay",
  },
  {
    id: "FG100XSH",
    slug: "fitguard-touch-nitrile-exam-gloves-100ct",
    sku: "FG100XSH",
    name: "FitGuard Touch Powder-Free Nitrile Exam Gloves",
    description: "FG TOUCH NITRILE EXAM GLOVES, 100CT,",
    category: "Nitrile Exam Gloves",
    manufacturer: "MEDLINE",
    price: 5.85,
    weight: "0.001 LB",
    image: "/ImageWithFallback.png",
    rating: 4.7,
    reviewCount: 156,
    workflowType: "self-pay",
  },
  {
    id: "SNAPSECUREFMH",
    slug: "snapsecure-foley-catheter-foam-device",
    sku: "SNAPSECUREFMH",
    name: "SnapSecure Foley Catheter Securement Devices",
    description: "SNAPSECURE FOAM FOLEY DEVICE",
    category: "Misc Urologicals",
    manufacturer: "MEDLINE",
    price: 4.57,
    weight: "0.046 LB",
    image: "/ImageWithFallback.png",
    rating: 4.2,
    reviewCount: 14,
    workflowType: "self-pay",
  },
  {
    id: "MDSP105611",
    slug: "cando-exercise-bands-yellow",
    sku: "MDSP105611",
    name: "Medline CanDo Non-Latex Exercise Bands",
    description: "BAND,EXERCISE,CANDO,LF,6YD,YELLOW,LVL1",
    category: "MB Exercise Supplies",
    manufacturer: "MEDLINE",
    price: 21.73,
    weight: "0.35 LB",
    image: "/ImageWithFallback.png",
    rating: 4.4,
    reviewCount: 22,
    workflowType: "self-pay",
  },
  {
    id: "PRM25855H",
    slug: "nonsterile-cotton-gauze-bandage-rolls",
    sku: "PRM25855H",
    name: "Medline Nonsterile Cotton Gauze Bandage Rolls",
    description: "BANDAGE,GAUZE,ROLL,4.5X4.1YD,NS,LF",
    category: "Bulkee Gauze/Bandage",
    manufacturer: "MEDLINE",
    price: 1.04,
    weight: "0.069 LB",
    image: "/ImageWithFallback.png",
    rating: 4.6,
    reviewCount: 37,
    workflowType: "self-pay",
  },
  {
    id: "MDS86100RF",
    slug: "toilet-safety-rails-aluminum",
    sku: "MDS86100RF",
    name: "Medline Toilet Safety Rails",
    description: "RAIL, TOILET SAFETY, ALUM,FOLD 250 LB",
    category: "Toilet, Wall and Tub",
    manufacturer: "MEDLINE",
    price: 20.78,
    weight: "4.7 LB",
    image: "/ImageWithFallback.png",
    rating: 4.8,
    reviewCount: 112,
    workflowType: "self-pay",
  },
  {
    id: "URO5458H",
    slug: "leg-bag-with-flip-drain",
    sku: "URO5458H",
    name: "Medline Leg Bag with Flip Drain",
    description: "BAG,LEG,FLIP-DRAIN SPOUT,LARGE,32 OZ",
    category: "Leg Bags",
    manufacturer: "MEDLINE",
    price: 5.03,
    weight: "0.119 LB",
    image: "/ImageWithFallback.png",
    rating: 4.3,
    reviewCount: 28,
    workflowType: "self-pay",
  },
  {
    id: "CURORT224MHH",
    slug: "curad-hernia-belts-medium",
    sku: "CURORT224MHH",
    name: "CURAD Hernia Belts",
    description: "BELT,HERNIA,ELASTIC,BLACK,RETAIL,M,1 EA",
    category: "Retail Ortho Soft Go",
    manufacturer: "MEDLINE",
    price: 19.74,
    weight: "0.4 LB",
    image: "/ImageWithFallback.png",
    rating: 4.1,
    reviewCount: 15,
    workflowType: "self-pay",
  },
  {
    id: "MSCPRC21616CS",
    slug: "gel-foam-wheelchair-cushions-16x16",
    sku: "MSCPRC21616CS",
    name: "Medline Gel Foam Wheelchair Cushions",
    description: "CUSHION,W/C, GEL FOAM CUSHION,16X16X2,CS",
    category: "Cushions and Wheel C",
    manufacturer: "MEDLINE",
    price: 68.58,
    weight: "16.3 LB",
    image: "/ImageWithFallback.png",
    rating: 4.5,
    reviewCount: 38,
    workflowType: "self-pay",
  },
  {
    id: "HUD1420",
    slug: "hudson-rci-oxygen-tubing-connectors",
    sku: "HUD1420",
    name: "Medline Hudson RCI Oxygen Supply Tubing Connectors",
    description: "CONNECTOR,OXYGEN,TUBING,STRAIGHT",
    category: "H O2 Accessories",
    manufacturer: "MEDLINE",
    price: 8.56,
    weight: "0.262 LB",
    image: "/ImageWithFallback.png",
    rating: 4.2,
    reviewCount: 19,
    workflowType: "self-pay",
  },
  {
    id: "CPAPTUBSL",
    slug: "standard-cpap-bipap-tubing-slim",
    sku: "CPAPTUBSL",
    name: "Medline Standard CPAP/BiPAP Tubing",
    description: "TUBING, 15MM, CPAP, SLIM, 6, 22MM CUFFS",
    category: "CPAP Masks and Acces",
    manufacturer: "MEDLINE",
    price: 26.71,
    weight: "2.5 LB",
    image: "/ImageWithFallback.png",
    rating: 4.7,
    reviewCount: 56,
    workflowType: "self-pay",
  },
  {
    id: "MSC263754H",
    slug: "fitright-aloe-wipes-68pk",
    sku: "MSC263754H",
    name: "FitRight Aloe Personal Cleansing Wipes",
    description: "WIPE, FITRIGHT, SCENTED, 68/PK",
    category: "Wet Wipes",
    manufacturer: "MEDLINE",
    price: 2.26,
    weight: "1.067 LB",
    image: "/ImageWithFallback.png",
    rating: 4.5,
    reviewCount: 42,
    workflowType: "self-pay",
  },
  {
    id: "MPH3550Z",
    slug: "evencare-g3-glucose-test-strips",
    sku: "MPH3550Z",
    name: "EvenCare G3 Blood Glucose Monitoring System",
    description: "STRIP,GLUCOSE,EVENCARE G3,PROF.USE ONLY",
    category: "EvenCare Diabetic",
    manufacturer: "MEDLINE",
    price: 6.98,
    weight: "0.1 LB",
    image: "/ImageWithFallback.png",
    rating: 4.3,
    reviewCount: 61,
    workflowType: "self-pay",
  },
  {
    id: "MDTPS4B08FPYH",
    slug: "terry-patient-slippers-bariatric",
    sku: "MDTPS4B08FPYH",
    name: "Medline Double-Tread Terry Patient Slippers",
    description: "SLIPPER,SUPER BARIATRIC,DBL TREAD,YE",
    category: "Slippers",
    manufacturer: "MEDLINE",
    price: 3.19,
    weight: "0.001 LB",
    image: "/ImageWithFallback.png",
    rating: 4.0,
    reviewCount: 12,
    workflowType: "self-pay",
  },
  {
    id: "DYNC1674H",
    slug: "urinary-drain-bags-2000ml",
    sku: "DYNC1674H",
    name: "Medline Urinary Drain Bags with Anti-Reflux Devices",
    description: "BAG,DRAINAGE,UROLOGY,2000ML,ANTI REFLUX",
    category: "Drainage Bags",
    manufacturer: "MEDLINE",
    price: 2.41,
    weight: "0.318 LB",
    image: "/ImageWithFallback.png",
    rating: 4.4,
    reviewCount: 34,
    workflowType: "self-pay",
  },
  {
    id: "COI50501HH",
    slug: "conveen-security-leg-bag-straps",
    sku: "COI50501HH",
    name: "Conveen Security Fabric Leg-Bag Straps",
    description: "STRAP,LEG BAG,L/F",
    category: "Coloplast-Ostomy",
    manufacturer: "COLOPLAST CORP",
    price: 5.32,
    weight: "0.65 LB",
    image: "/ImageWithFallback.png",
    rating: 4.6,
    reviewCount: 27,
    workflowType: "self-pay",
  },
];
