import type { Product } from "@/types/product";

export const PRODUCTS: Product[] = [
  {
    "id": "MDR107002E",
    "slug": "medline-basic-homecare-beds",
    "sku": "MDR107002E",
    "name": "Medline Basic Homecare Beds",
    "description": "BED,BASIC, SEMI ELECTRIC, 450 LB",
    "category": "Furniture & Capital Equipment",
    "group": "Home Care Beds",
    "manufacturer": "MEDLINE",
    "price": 244.41,
    "weight": "166.22 LB",
    "hcpcs": "E0295",
    "billingUomUnits": "EACH",
    "uomSetName": "EACH",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "MSCADVHC80",
    "slug": "advantage-therapeutic-homecare-foam-mattresses",
    "sku": "MSCADVHC80",
    "name": "Advantage Therapeutic Homecare Foam Mattresses",
    "description": "MATTRESS, ADVANTAGE, HOMECARE, 36X80X6",
    "category": "Body Positioning",
    "group": "Post-Acute Foam Matt",
    "manufacturer": "MEDLINE",
    "price": 107.10,
    "weight": "21.5 LB",
    "hcpcs": "E0184",
    "billingUomUnits": "EACH",
    "uomSetName": "EACH",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "FCE1385B",
    "slug": "alterra-1385-hi-low-long-term-care-hospital-beds",
    "sku": "FCE1385B",
    "name": "Alterra 1385 Hi/Low Long-Term Care Hospital Beds",
    "description": "BED ONLY,4-MOTOR,HI/LOW,34.5W,LOCK",
    "category": "Furniture & Capital Equipment",
    "group": "Long Term Care Beds",
    "manufacturer": "MEDLINE",
    "price": 896.40,
    "weight": "240.301 LB",
    "billingUomUnits": "EACH",
    "uomSetName": "EACH",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "MDR107004L",
    "slug": "medline-bariatric-homecare-beds",
    "sku": "MDR107004L",
    "name": "Medline Bariatric Homecare Beds",
    "description": "BED, BARIATRIC, LIGHTWEIGHT, 42 W",
    "category": "Furniture & Capital Equipment",
    "group": "Home Care Beds",
    "manufacturer": "MEDLINE",
    "price": 680.00,
    "weight": "208.78 LB",
    "hcpcs": "E0295",
    "billingUomUnits": "EACH",
    "uomSetName": "EACH",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "MDR107003E",
    "slug": "medline-basic-homecare-beds-full-electric",
    "sku": "MDR107003E",
    "name": "Medline Basic Homecare Beds",
    "description": "BED, BASIC, FULL ELECTRIC, 450 LB",
    "category": "Furniture & Capital Equipment",
    "group": "Home Care Beds",
    "manufacturer": "MEDLINE",
    "price": 339.51,
    "weight": "159 LB",
    "hcpcs": "E0297",
    "billingUomUnits": "EACH",
    "uomSetName": "EACH",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "K1186V22E",
    "slug": "guardian-k1-wheelchairs",
    "sku": "K1186V22E",
    "name": "Guardian K1 Wheelchairs",
    "description": "WC,K1,VINYL,18,SB DLA,ELR, 300 LB",
    "category": "Patient Safety & Mobility",
    "group": "HME Wheelchairs",
    "manufacturer": "MEDLINE",
    "price": 98.00,
    "weight": "50.2 LB",
    "hcpcs": "K0006 + K0195",
    "billingUomUnits": "EACH",
    "uomSetName": "EACH",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "MDS88200D",
    "slug": "medline-manual-hydraulic-patient-lift",
    "sku": "MDS88200D",
    "name": "Medline Manual Hydraulic Patient Lift",
    "description": "LIFT,PATIENT,HYDRAULIC,6 POINT CRADLE",
    "category": "Patient Safety & Mobility",
    "group": "Medline Hydraulic Li",
    "manufacturer": "MEDLINE",
    "price": 290.52,
    "weight": "80.5 LB",
    "hcpcs": "E0630",
    "billingUomUnits": "EACH",
    "uomSetName": "EACH",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "MDR211892R",
    "slug": "medline-premium-foam-homecare-mattresses",
    "sku": "MDR211892R",
    "name": "Medline Premium Foam Homecare Mattresses",
    "description": "MATTRESS,FOAM,42X84X6",
    "category": "Body Positioning",
    "group": "Home Care Beds-A",
    "manufacturer": "MEDLINE",
    "price": 150.00,
    "weight": "28.2 LB",
    "hcpcs": "E0272",
    "billingUomUnits": "EACH",
    "uomSetName": "EACH",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "KX228V21E",
    "slug": "guardian-extra-wide-wheelchairs",
    "sku": "KX228V21E",
    "name": "Guardian Extra-Wide Wheelchairs",
    "description": "WC, XW, 22, RDLA, ELR, 500 LB",
    "category": "Patient Safety & Mobility",
    "group": "HME Wheelchairs",
    "manufacturer": "MEDLINE",
    "price": 172.25,
    "weight": "65.918 LB",
    "hcpcs": "K0007 + E2201 + K0195",
    "billingUomUnits": "EACH",
    "uomSetName": "EACH",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "MDT24A10",
    "slug": "medline-a10-lal-alternating-pressure-mattress-system",
    "sku": "MDT24A10",
    "name": "Medline A10 LAL / Alternating Pressure Mattress System",
    "description": "MATTRESS,SYSTEM,A10,LAL/ALTERNATING",
    "category": "Body Positioning",
    "group": "Powered Surfaces",
    "manufacturer": "MEDLINE",
    "price": 211.89,
    "weight": "24.1 LB",
    "hcpcs": "E0277",
    "billingUomUnits": "EACH",
    "uomSetName": "EACH",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "MDTSUPAIRB42",
    "slug": "medline-supra-air-bariatric-mattresses",
    "sku": "MDTSUPAIRB42",
    "name": "Medline Supra Air Bariatric Mattresses",
    "description": "LAL MATTRESS,BARI SUPRA AIR 42",
    "category": "Body Positioning",
    "group": "Powered Surfaces",
    "manufacturer": "MEDLINE",
    "price": 672.18,
    "weight": "34.75 LB",
    "hcpcs": "E0277",
    "billingUomUnits": "EACH",
    "uomSetName": "EACH",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "COSB337",
    "slug": "instant-wide-long-term-care-low-bed",
    "sku": "COSB337",
    "name": "Instant Wide Long-Term Care Low Bed",
    "description": "LOW BED,LTC,INSTANT WIDE,600LB,36-42W",
    "category": "Furniture & Capital Equipment",
    "group": "Long Term Care Beds",
    "manufacturer": "COSTCARE",
    "price": 1216.73,
    "weight": "291 LB",
    "billingUomUnits": "EACH",
    "uomSetName": "EACH",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "MDS89697",
    "slug": "medline-half-rail-for-medline-homecare-beds",
    "sku": "MDS89697",
    "name": "Medline Half Rail for Medline Homecare Beds",
    "description": "RAIL,CLAMP-ON HALF F/ MEDLINE HMC",
    "category": "Furniture & Capital Equipment",
    "group": "Home Care Beds",
    "manufacturer": "MEDLINE",
    "price": 29.89,
    "weight": "18 LB",
    "hcpcs": "E0305",
    "billingUomUnits": "CASE",
    "uomSetName": "CASE",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "K1206V22E",
    "slug": "guardian-k1-wheelchairs-20",
    "sku": "K1206V22E",
    "name": "Guardian K1 Wheelchairs",
    "description": "WC,K1,VINYL,20,SB DLA,ELR, 300 LB",
    "category": "Patient Safety & Mobility",
    "group": "HME Wheelchairs",
    "manufacturer": "MEDLINE",
    "price": 105.00,
    "weight": "50.2 LB",
    "hcpcs": "K0006 + E2201 + K0195",
    "billingUomUnits": "EACH",
    "uomSetName": "EACH",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "MDS86410W54",
    "slug": "medline-two-button-folding-walkers-with-5-wheels",
    "sku": "MDS86410W54",
    "name": "Medline Two-Button Folding Walkers with 5\" Wheels",
    "description": "WALKER,2 BUTTON, W/5 INCH WHLS, 300 LB",
    "category": "Patient Safety & Mobility",
    "group": "Walkers",
    "manufacturer": "MEDLINE",
    "price": 84.00,
    "weight": "30.1 LB",
    "hcpcs": "E0143",
    "billingUomUnits": "CASE",
    "uomSetName": "CASE",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "MDS86850EBS8",
    "slug": "medline-basic-steel-rollators-blue",
    "sku": "MDS86850EBS8",
    "name": "Medline Basic Steel Rollators",
    "description": "ROLLATOR,BASIC,STEEL,8,BLUE",
    "category": "Patient Safety & Mobility",
    "group": "Rollators",
    "manufacturer": "MEDLINE",
    "price": 54.04,
    "weight": "20.72 LB",
    "hcpcs": "E0143 + E0156",
    "billingUomUnits": "EACH",
    "uomSetName": "EACH",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "MDS86830EBLS8",
    "slug": "medline-basic-steel-rollators-black",
    "sku": "MDS86830EBLS8",
    "name": "Medline Basic Steel Rollators",
    "description": "ROLLATOR, BASIC, BLACK, STEEL, 8",
    "category": "Patient Safety & Mobility",
    "group": "Rollators",
    "manufacturer": "MEDLINE",
    "price": 54.04,
    "weight": "15 LB",
    "hcpcs": "E0143 + E0156",
    "billingUomUnits": "EACH",
    "uomSetName": "EACH",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "MDS808550",
    "slug": "medline-excel-reclining-wheelchairs",
    "sku": "MDS808550",
    "name": "Medline Excel Reclining Wheelchairs",
    "description": "WC,RECL,20,DLA,ELR, 300 LB",
    "category": "Patient Safety & Mobility",
    "group": "HME Wheelchairs",
    "manufacturer": "MEDLINE",
    "price": 185.00,
    "weight": "30.26 LB",
    "hcpcs": "K0003 + E0966 + E1226 + K0195 + E0971 + E2201",
    "billingUomUnits": "EACH",
    "uomSetName": "EACH",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "FCE1232RSRN",
    "slug": "alterra-bed-side-rails",
    "sku": "FCE1232RSRN",
    "name": "Alterra Bed Side Rails",
    "description": "RAIL,SIDE,HEAD SECTION,SOFT TOUCH",
    "category": "Furniture & Capital Equipment",
    "group": "Long Term Care Beds",
    "manufacturer": "MEDLINE",
    "price": 75.60,
    "weight": "27.558 LB",
    "hcpcs": "E0305",
    "billingUomUnits": "PAIR",
    "uomSetName": "PAIR",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "MDS86800XW",
    "slug": "medline-heavy-duty-bariatric-rollators",
    "sku": "MDS86800XW",
    "name": "Medline Heavy-Duty Bariatric Rollators",
    "description": "ROLLATOR,X-WIDE,8 WHL,400 LBS.",
    "category": "Patient Safety & Mobility",
    "group": "Rollators",
    "manufacturer": "MEDLINE",
    "price": 100.08,
    "weight": "24.03 LB",
    "hcpcs": "E0149 + E0156",
    "billingUomUnits": "EACH",
    "uomSetName": "EACH",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "FCE1232RHFQO2",
    "slug": "traditional-style-headboards-and-footboards",
    "sku": "FCE1232RHFQO2",
    "name": "Traditional Style Headboards and Footboards",
    "description": "BOARD,HEAD/FOOT,TRDTNL,SOLAR OAK,36W,QS",
    "category": "Furniture & Capital Equipment",
    "group": "Long Term Care Beds",
    "manufacturer": "STEVENS INDUSTRIES, INC.",
    "price": 81.00,
    "weight": "24 LB",
    "billingUomUnits": "PAIR",
    "uomSetName": "PAIR",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "MDS500TPZ",
    "slug": "medline-lightweight-bariatric-trapeze",
    "sku": "MDS500TPZ",
    "name": "Medline Lightweight Bariatric Trapeze",
    "description": "TRAPEZE, BAR, 500 POUNDS, W/BASE",
    "category": "Furniture & Capital Equipment",
    "group": "Home Care Beds",
    "manufacturer": "MEDLINE",
    "price": 190.35,
    "weight": "62.6 LB",
    "hcpcs": "E0912",
    "billingUomUnits": "EACH",
    "uomSetName": "EACH",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "MDS926301",
    "slug": "medline-sprague-rappaport-stethoscopes",
    "sku": "MDS926301",
    "name": "Medline Sprague Rappaport Stethoscopes",
    "description": "STETHOSCOPE,SPRAGUE RAPPAPORT,BLACK",
    "category": "Exam & Diagnostic Supplies",
    "group": "Stethoscopes",
    "manufacturer": "MEDLINE",
    "price": 12.58,
    "weight": "0.669 LB",
    "billingUomUnits": "EACH",
    "uomSetName": "EACH",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "MDSBEDCART",
    "slug": "medline-bed-transport-carts",
    "sku": "MDSBEDCART",
    "name": "Medline Bed Transport Carts",
    "description": "KIT,BED CART,FOR HOMECARE BED",
    "category": "Furniture & Capital Equipment",
    "group": "Bed Parts",
    "manufacturer": "MEDLINE",
    "price": 25.00,
    "weight": "9.04 LB",
    "billingUomUnits": "CASE",
    "uomSetName": "CASE",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "K1206V22S",
    "slug": "guardian-k1-wheelchairs-sa",
    "sku": "K1206V22S",
    "name": "Guardian K1 Wheelchairs",
    "description": "WC,K1,VINYL,20,SB DLA,SA, 300 LB",
    "category": "Patient Safety & Mobility",
    "group": "HME Wheelchairs",
    "manufacturer": "MEDLINE",
    "price": 95.00,
    "weight": "50.2 LB",
    "hcpcs": "K0006 + E2201",
    "billingUomUnits": "EACH",
    "uomSetName": "EACH",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "MSC8801EPZ",
    "slug": "puracol-ultra-powder-collagen-wound-dressings",
    "sku": "MSC8801EPZ",
    "name": "Puracol Ultra Powder Collagen Wound Dressings",
    "description": "COLLAGEN, PARTICLES, PURACOL ULTRA, 1G",
    "group": "Puracol Ultra",
    "manufacturer": "MEDLINE",
    "price": 232.25,
    "weight": "1 LB",
    "hcpcs": "A6010",
    "billingUomUnits": "BOX",
    "uomSetName": "BOX",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "MDS89697BARL",
    "slug": "medline-bariatric-head-foot-section-rails",
    "sku": "MDS89697BARL",
    "name": "Medline Bariatric Head / Foot Section Rails",
    "description": "RAIL, HALF, BARIATRIC, F/MDR107004L",
    "category": "Furniture & Capital Equipment",
    "group": "Home Care Beds",
    "manufacturer": "MEDLINE",
    "price": 50.00,
    "weight": "20.5 LB",
    "hcpcs": "E0305",
    "billingUomUnits": "PAIR",
    "uomSetName": "PAIR",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "MSCPRC21816CS",
    "slug": "medline-gel-foam-wheelchair-cushions-for-pressure-redistribution-18x16",
    "sku": "MSCPRC21816CS",
    "name": "Medline Gel Foam Wheelchair Cushions for Pressure Redistribution",
    "description": "CUSHION,W/C, GEL FOAM CUSHION,18X16X2,CS",
    "category": "Patient Safety & Mobility",
    "group": "Cushions and Wheel C",
    "manufacturer": "MEDLINE",
    "price": 88.38,
    "weight": "17.55 LB",
    "hcpcs": "E2601",
    "billingUomUnits": "CASE",
    "uomSetName": "CASE",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "BDD442021",
    "slug": "bd-bactec-lytic-anaerobic-medium",
    "sku": "BDD442021",
    "name": "BD BACTEC Lytic Anaerobic Medium",
    "description": "BACTEC, LYTIC ANAEROBIC, PLASTIC",
    "group": "BD Bactec Kits",
    "manufacturer": "BD",
    "price": 324.81,
    "weight": "7.7 LB",
    "billingUomUnits": "PACK",
    "uomSetName": "PACK",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "MSCPRC22016CS",
    "slug": "medline-gel-foam-wheelchair-cushions-for-pressure-redistribution-20x16",
    "sku": "MSCPRC22016CS",
    "name": "Medline Gel Foam Wheelchair Cushions for Pressure Redistribution",
    "description": "CUSHION,W/C, GEL FOAM CUSHION,20X16X2,CS",
    "category": "Patient Safety & Mobility",
    "group": "Cushions and Wheel C",
    "manufacturer": "MEDLINE",
    "price": 72.19,
    "weight": "19.55 LB",
    "hcpcs": "E2601",
    "billingUomUnits": "CASE",
    "uomSetName": "CASE",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "MSC8444H",
    "slug": "puracol-ag-silver-collagen-wound-dressings",
    "sku": "MSC8444H",
    "name": "Puracol Ag+ Silver Collagen Wound Dressings",
    "description": "DRESSING,COLLAGEN,PURACOL WITH AG,4X",
    "group": "Puracol",
    "manufacturer": "MEDLINE",
    "price": 26.35,
    "weight": "0.001 LB",
    "hcpcs": "A6022",
    "billingUomUnits": "EACH",
    "uomSetName": "EACH",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "COSBPR300",
    "slug": "long-term-care-bed-assist-rails",
    "sku": "COSBPR300",
    "name": "Long-Term Care Bed Assist Rails",
    "description": "RAILS, ASSIST, COMPOSITE, SWING DOWN,",
    "category": "Furniture & Capital Equipment",
    "group": "Long Term Care Beds",
    "manufacturer": "COSTCARE",
    "price": 151.03,
    "weight": "17.4 LB",
    "billingUomUnits": "PAIR",
    "uomSetName": "PAIR",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "MDS86800XWS",
    "slug": "medline-heavy-duty-bariatric-rollators-steel",
    "sku": "MDS86800XWS",
    "name": "Medline Heavy-Duty Bariatric Rollators",
    "description": "ROLLATOR, BARIATRIC, BASIC STEEL",
    "category": "Patient Safety & Mobility",
    "group": "Rollators",
    "manufacturer": "MEDLINE",
    "price": 79.21,
    "weight": "26.5 LB",
    "hcpcs": "E0149 + E0156",
    "billingUomUnits": "EACH",
    "uomSetName": "EACH",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "COSBPW337",
    "slug": "head-and-footboards",
    "sku": "COSBPW337",
    "name": "Head and Footboards",
    "description": "BOARD, HEAD/FOOT, CHY / OAK, FOR COSB337",
    "category": "Furniture & Capital Equipment",
    "group": "Long Term Care Beds",
    "manufacturer": "COSTCARE",
    "price": 273.21,
    "weight": "31.8 LB",
    "billingUomUnits": "PAIR",
    "uomSetName": "PAIR",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "G2-100KHX1",
    "slug": "medline-shower-chair-with-arms-and-back",
    "sku": "G2-100KHX1",
    "name": "Medline Shower Chair with Arms and Back",
    "description": "CHAIR, SHOWER  , W/BACK ARMRESTS, 350 LB",
    "category": "Patient Safety & Mobility",
    "group": "Shower Chairs",
    "manufacturer": "MEDLINE",
    "price": 30.32,
    "weight": "8.818 LB",
    "hcpcs": "E0240",
    "billingUomUnits": "EACH",
    "uomSetName": "EACH",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "FCE42KIT",
    "slug": "medline-bed-extenders-for-alterra-beds",
    "sku": "FCE42KIT",
    "name": "Medline Bed Extenders for Alterra Beds",
    "description": "KIT,EXTENSION,WIDTH,42 WIDE",
    "category": "Furniture & Capital Equipment",
    "group": "Long Term Care Beds",
    "manufacturer": "MEDLINE",
    "price": 146.18,
    "weight": "24.251 LB",
    "billingUomUnits": "EACH",
    "uomSetName": "EACH",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "RLL-230A-8B",
    "slug": "medline-basic-rollators-blue",
    "sku": "RLL-230A-8B",
    "name": "Medline Basic Rollators",
    "description": "ROLLATOR, BASIC, BLUE, 8, 300 LB",
    "category": "Patient Safety & Mobility",
    "group": "Rollators",
    "manufacturer": "MEDLINE",
    "price": 56.10,
    "weight": "19.85 LB",
    "hcpcs": "E0143 + E0156",
    "billingUomUnits": "EACH",
    "uomSetName": "EACH",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "RLL-230A-8BG",
    "slug": "medline-basic-rollators-burgundy",
    "sku": "RLL-230A-8BG",
    "name": "Medline Basic Rollators",
    "description": "ROLLATOR, BASIC, BURGUNDY, 8, 300 LB",
    "category": "Patient Safety & Mobility",
    "group": "Rollators",
    "manufacturer": "MEDLINE",
    "price": 56.10,
    "weight": "20.45 LB",
    "hcpcs": "E0143 + E0156",
    "billingUomUnits": "EACH",
    "uomSetName": "EACH",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "MSC2148H",
    "slug": "optifoam-gentle-post-op-foam-wound-dressings",
    "sku": "MSC2148H",
    "name": "Optifoam Gentle Post-Op Foam Wound Dressings",
    "description": "OPTIFOAM GENTLE SA,POST-OP,4X8",
    "group": "Post-Op Dressings",
    "manufacturer": "MEDLINE",
    "price": 8.88,
    "weight": "0.035 LB",
    "hcpcs": "A6254",
    "billingUomUnits": "EACH",
    "uomSetName": "EACH",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "PVC513",
    "slug": "basic-medical-powder-free-clear-vinyl-exam-gloves",
    "sku": "PVC513",
    "name": "Basic Medical Powder-Free Clear Vinyl Exam Gloves",
    "description": "GLOVE,EXAM,VINYL,PF,LF,CLEAR,LARGE",
    "group": "Vinyl Exam Gloves -",
    "manufacturer": "BASIC MEDICAL INDUSTRIES INC",
    "price": 34.87,
    "weight": "19.95 LB",
    "billingUomUnits": "CASE",
    "uomSetName": "CASE",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "G1-301DX2",
    "slug": "medline-steel-drop-arm-commodes",
    "sku": "G1-301DX2",
    "name": "Medline Steel Drop-Arm Commodes",
    "description": "COMMODE, STEEL, DROP ARM, 350 LB",
    "category": "Patient Safety & Mobility",
    "group": "Commode",
    "manufacturer": "MEDLINE",
    "price": 87.20,
    "weight": "48.7 LB",
    "hcpcs": "E0165",
    "billingUomUnits": "CASE",
    "uomSetName": "CASE",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "FCE1232HDW",
    "slug": "medline-headboard-footboard-mounting-hardware",
    "sku": "FCE1232HDW",
    "name": "Medline Headboard/Footboard Mounting Hardware",
    "description": "HARDWARE,MOUNTING,F/1232 H/F BOARDS",
    "category": "Furniture & Capital Equipment",
    "group": "Long Term Care Beds",
    "manufacturer": "MEDLINE",
    "price": 19.44,
    "weight": "8.8 LB",
    "hcpcs": "A9900",
    "billingUomUnits": "EACH",
    "uomSetName": "EACH",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "MKNMM0049H",
    "slug": "manukapli-sterile-honey-wound-dressing-gel",
    "sku": "MKNMM0049H",
    "name": "MANUKApli Sterile Honey Wound Dressing Gel",
    "description": "DBF-SEE GEWMM0049H HONEY,MANUKA PLI,0.5O",
    "group": "Gentell, Inc.",
    "manufacturer": "MANUKAMED",
    "price": 10.10,
    "weight": "0.1 LB",
    "billingUomUnits": "EACH",
    "uomSetName": "EACH",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "FG100M",
    "slug": "fitguard-touch-powder-free-nitrile-exam-gloves",
    "sku": "FG100M",
    "name": "FitGuard Touch Powder-Free Nitrile Exam Gloves",
    "description": "FG TOUCH NITRILE EXAM GLOVES, 100CT, MD",
    "group": "Nitrile Exam Gloves",
    "manufacturer": "MEDLINE",
    "price": 58.27,
    "weight": "8.4 LB",
    "hcpcs": "A4927",
    "billingUomUnits": "CASE",
    "uomSetName": "CASE",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "FCET01RHFXW",
    "slug": "traditional-style-headboards-and-footboards-42",
    "sku": "FCET01RHFXW",
    "name": "Traditional Style Headboards and Footboards",
    "description": "BOARD,HEAD/FOOT,F/42",
    "category": "Furniture & Capital Equipment",
    "group": "Long Term Care Beds",
    "manufacturer": "STEVENS INDUSTRIES, INC.",
    "price": 135.96,
    "weight": "50 LB",
    "billingUomUnits": "EACH",
    "uomSetName": "EACH",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "HCS70004",
    "slug": "aeromist-compact-nebulizer-compressor",
    "sku": "HCS70004",
    "name": "Aeromist Compact Nebulizer Compressor",
    "description": "COMPRESSOR,NEBULIZER,AEROMIST COMPACT",
    "group": "Nebulizer Compressor",
    "manufacturer": "MEDLINE",
    "price": 152.27,
    "weight": "26.85 LB",
    "hcpcs": "E0570",
    "billingUomUnits": "CASE",
    "uomSetName": "CASE",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "MSC64610EPH",
    "slug": "optilock-nonadhesive-super-absorbent-wound-dressings",
    "sku": "MSC64610EPH",
    "name": "OptiLock Nonadhesive Super Absorbent Wound Dressings",
    "description": "OPTILOCK,NON-ADHESIVE,6.5X10",
    "group": "Absorbent Dressings",
    "manufacturer": "MEDLINE",
    "price": 8.68,
    "weight": "0.1 LB",
    "hcpcs": "A6198",
    "billingUomUnits": "EACH",
    "uomSetName": "EACH",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "ADC427PKH",
    "slug": "adtemp-427-temple-touch-thermometers",
    "sku": "ADC427PKH",
    "name": "Adtemp 427 Temple-Touch Thermometers",
    "description": "THERMOMETER,TEMPLE TOUCH",
    "category": "Exam & Diagnostic Supplies",
    "group": "American Diagnostic",
    "manufacturer": "AMERICAN DIAGNOSTIC CORP",
    "price": 20.43,
    "weight": "0.042 LB",
    "billingUomUnits": "EACH",
    "uomSetName": "EACH",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "MDS104015",
    "slug": "medline-economy-overbed-tables",
    "sku": "MDS104015",
    "name": "Medline Economy Overbed Tables",
    "description": "TABLE, OVERBED, WALNUT",
    "category": "Furniture & Capital Equipment",
    "group": "Overbed Tables Stock",
    "manufacturer": "MEDLINE",
    "price": 32.99,
    "weight": "22 LB",
    "hcpcs": "E0274",
    "billingUomUnits": "EACH",
    "uomSetName": "EACH",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  },
  {
    "id": "G3-100KBX2",
    "slug": "medline-transfer-benches-with-backrest",
    "sku": "G3-100KBX2",
    "name": "Medline Transfer Benches with Backrest",
    "description": "BENCH,TRANSFER,BACK,PUSH BUTTONS, 400 LB",
    "category": "Patient Safety & Mobility",
    "group": "Transfer Benches",
    "manufacturer": "MEDLINE",
    "price": 67.43,
    "weight": "26.85 LB",
    "hcpcs": "E0247",
    "billingUomUnits": "CASE",
    "uomSetName": "CASE",
    "status": "ACTIVE",
    "image": "/ImageWithFallback.png",
    "rating": 4.5,
    "reviewCount": 30,
    "workflowType": "self-pay"
  }
];
